sources:
  "3.13.1":
    url: "https://www.python.org/ftp/python/3.13.1/Python-3.13.1.tgz"
    sha256: "1513925a9f255ef0793dbf2f78bb4533c9f184bdd0ad19763fd7f47a400a7c55"
  "3.12.8":
    url: "https://www.python.org/ftp/python/3.12.8/Python-3.12.8.tgz"
    sha256: "5978435c479a376648cb02854df3b892ace9ed7d32b1fead652712bee9d03a45"
  "3.11.11":
    url: "https://www.python.org/ftp/python/3.11.11/Python-3.11.11.tgz"
    sha256: "883bddee3c92fcb91cf9c09c5343196953cbb9ced826213545849693970868ed"
  "3.10.16":
    url: "https://www.python.org/ftp/python/3.10.16/Python-3.10.16.tgz"
    sha256: "f2e22ed965a93cfeb642378ed6e6cdbc127682664b24123679f3d013fafe9cd0"
  "3.9.21":
    url: "https://www.python.org/ftp/python/3.9.21/Python-3.9.21.tgz"
    sha256: "667c3ba2ca98d39ead1162f6548c3475768582e2ff89e0821d25eb956ac09944"
  "3.8.20":
    url: "https://www.python.org/ftp/python/3.8.20/Python-3.8.20.tgz"
    sha256: "9f2d5962c2583e67ef75924cd56d0c1af78bf45ec57035cf8a2cc09f74f4bf78"
patches:
  "3.13.1":
    - patch_file: "patches/0001-limit-makefile-3.13.1.patch"
  "3.12.8":
    - patch_file: "patches/0001-limit-makefile-3.12.8.patch"
  "3.11.11":
    - patch_file: "patches/0001-limit-makefile-3.11.11.patch"
  "3.10.16":
    - patch_file: "patches/0001-limit-makefile-3.10.16.patch"
  "3.9.21":
    - patch_file: "patches/0001-limit-makefile-3.9.21.patch"
    - patch_file: "patches/0002-libpython.a-test-existence-3.9.21.patch"
  "3.8.20":
    - patch_file: "patches/0001-limit-makefile-3.8.20.patch"
    - patch_file: "patches/0002-python-config-mkdir-3.8.20.patch"
    - patch_file: "patches/0003-libpython.a-test-existence-3.8.20.patch"
